NAMA : ARIO SYAWAL MUHAMMAD  
NIM : 1103201243

In [3]:
import pandas as pd

data=data = pd.read_csv("edge_message_correlation_edit.csv")
data.head(10)

,Edge,Severity,Device_is_not_communicating_with_the_Orchestrator,Edge_USB_device_inserted,Invalid_device_settings_detected_configuration_may_be_incorrect,Link_GE3_is_now_DEAD,Link_GE4_is_now_DEAD
0,PM-VELO-TLKM-01,Alert,2,8,6,0,0
1,RMP-VELO-TLKM-01,Alert,2,8,4,0,0
2,RTR0063201,Alert,28,2,22,0,168
3,RTR0067501,Alert,26,2,14,54,82
4,RTR0312601,Error,61,2,97,30,40
5,RTR0317601,Alert,11,2,3,86,123
6,RTR0318301,Alert,18,2,17,40,95
7,RTR0318601,Alert,3,2,3,37,67
8,RTR0318701,Error,24,4,53,0,59
9,RTR0319001,Alert,8,6,19,8,39

In [4]:
data.describe()

,Device_is_not_communicating_with_the_Orchestrator,Edge_USB_device_inserted,Invalid_device_settings_detected_configuration_may_be_incorrect,Link_GE3_is_now_DEAD,Link_GE4_is_now_DEAD
count,303.000000,303.000000,303.000000,303.000000,303.000000
mean,35.412541,5.174917,33.056106,49.864686,108.894389
std,36.420986,9.051312,53.063627,127.856364,168.861150
min,1.000000,0.000000,0.000000,0.000000,0.000000
25%,12.000000,2.000000,5.000000,3.000000,41.000000
50%,22.000000,2.000000,16.000000,18.000000,67.000000
75%,46.000000,4.000000,41.500000,47.000000,104.000000
max,250.000000,92.000000,493.000000,1281.000000,1994.000000